{% set name = "gst-plugins-ugly" %}
{% set version = "1.24.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-{{ version }}.tar.xz
  sha256: 3a1f58a33aee8d13522865bcb564007a6837ef5711d7dfff8ce4260921013f8a
build:
  number: 03a1f58a33aee8d13522865bcb564007a6837ef5711d7dfff8ce4260921013f8a
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-plugins-ugly', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - pkg-config
    - meson
    - ninja
    - gettext-tools
  host:
    - libgl-devel                        # [linux]
    - libegl-devel                       # [linux]
    - libdrm                             # [linux]
    - libiconv
    - libintl-devel                      # [not linux]
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - gobject-introspection
    - glib
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - x264
    - zlib
    - expat                              # [linux]
    - xorg-xorgproto                     # [linux]
    - xorg-libxfixes                     # [linux]
    - xorg-libxext                       # [linux]
    - xorg-libx11                        # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-libxau                        # [linux]
  run:
    # We want to pin harder than the run_export from gstreamer
    - gstreamer         {{ version }}
test:
  commands:
    - test -f $PREFIX/lib/gstreamer-1.0/libgstasf${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdlpcmdec${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdsub${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstrealmedia${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstx264${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstasf.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdlpcmdec.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdsub.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstrealmedia.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstx264.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin x264

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GStreamer Ugly Plug-ins
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
