{% set name = "gst-plugins-ugly" %}
{% set version = "1.24.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-{{ version }}.tar.xz
  sha256: 4b6b30110f38cd05eb67422297142b75a55fe00003105f48b13603e6761cc3b6
build:
  number: 0
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-plugins-ugly', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # expat here is _only_ required for mesa-dri-drivers
    - {{ cdt('libselinux-devel') }}      # [linux]
    #- x264
    - pkg-config
    #- perl
    - meson
    - ninja
    - gettext-tools
  host:
    - libiconv
    - libintl-devel                      # [not linux]
    - gstreamer         {{ version }}
    - gst-plugins-base  {{ version }}
    - gobject-introspection
    - glib
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - x264
    - xorg-libxfixes                     # [linux]
    - xorg-libxext                       # [linux]
    - xorg-xproto                        # [linux]
    - xorg-libx11                        # [linux]
    - expat                              # [linux]
    - xorg-libxrender                    # [linux]
    - xorg-libxdamage                    # [linux]
    - xorg-libxxf86vm                    # [linux]
    - xorg-libxau                        # [linux]
  run:
    # We want to pin harder than the run_export from gstreamer
    - gstreamer         {{ version }}
test:
  commands:
    - test -f $PREFIX/lib/gstreamer-1.0/libgstasf${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdlpcmdec${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdsub${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstrealmedia${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstx264${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstasf.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdlpcmdec.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdsub.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstrealmedia.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstx264.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin x264

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GStreamer Ugly Plug-ins
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
    - hmaarrfk
