{% set name = "gst-plugins-ugly" %}
{% set version = "1.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gstreamer.freedesktop.org/src/gst-plugins-ugly/gst-plugins-ugly-{{ version }}.tar.xz
  sha256: 34dd6f4a44db30a7b171223e7789d863febe5aa20991cf920b0d25191968393c

build:
  number: 0
  run_exports:
    # remove symbols at .90 patch releases just before minor versions?
    #    https://abi-laboratory.pro/tracker/timeline/gstreamer/
    - {{ pin_subpackage('gst-plugins-ugly', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('libdrm-devel') }}          # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    # expat here is _only_ required for mesa-dri-drivers
    - {{ cdt('expat') }}                 # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    #- x264
    - pkg-config
    #- perl
    - meson
    - ninja
  host:
    - libiconv
    - gstreamer
    - gst-plugins-base
    - gobject-introspection
    - glib
    - gettext                            # [osx]
    - libxcb                             # [linux]
    - pthread-stubs                      # [linux]
    - x264

test:
  commands:
    - test -f $PREFIX/lib/gstreamer-1.0/libgstasf${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdlpcmdec${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstdvdsub${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstrealmedia${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstx264${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/lib/gstreamer-1.0/libgstxingmux${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstasf.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdlpcmdec.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstdvdsub.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstrealmedia.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstx264.dll exit 1  # [win]
    - if not exist %LIBRARY_LIB%\\gstreamer-1.0\\gstxingmux.dll exit 1  # [win]
    - gst-inspect-1.0 --plugin x264

about:
  home: http://gstreamer.freedesktop.org/
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: GStreamer Ugly Plug-ins
  dev_url: https://gitlab.freedesktop.org/gstreamer/gst-plugins-ugly

extra:
  recipe-maintainers:
    - scopatz
    - kuepe-sl
